# Generated by Django 6.1.1 on 2026-10-04 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="document",
            name="previous_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_versions",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
